### ISSUE TITLE
bug: shouldn't allow connecting multiple parents to the same node

### ISSUE THREAD

**Issue by kryptoklob** [transmissions11/flux#13]
was playing around with connecting random things and got this
which does nothing (I think?)

<img width="670" alt="image" src="https://user-images.githubusercontent.com/8293474/228425666-0cad196d-fde3-4533-93cb-26998f8195c3.png">

**Comment by transmissions11** [comment]
i'd narrow this more specifically down to "shouldnt allow connecting multiple parents to a single node" which is pretty tractable if you wanna try PR-ing!
