### ISSUE TITLE
feat: editing response textboxes should stop GPT generation

### ISSUE THREAD

**Issue by transmissions11** [transmissions11/flux#16]

**Comment by transmissions11** [comment]
alternative: if you edit the textbox while its generating, it stops streaming in the response immediately

**Comment by h0tw4t3r** [comment]
> alternative: if you edit the textbox while its generating, it stops streaming in the response immediately

Would be best to do like that with proper debouncing.

**Comment by transmissions11** [comment]
@h0tw4t3r can you explain how debouncing comes into play here? i think we'd just mark the node as non generating and then can update the openai streaming logic to check a node is still marked as generating before appending text

**Comment by h0tw4t3r** [comment]
> @h0tw4t3r can you explain how debouncing comes into play here? i think we'd just mark the node as non generating and then can update the openai streaming logic to check a node is still marked as generating before appending text

oh I'm sorry, taking my words back. I thought about not just stopping the request but reinitiating it on text change.

**Comment by ghgoodreau** [comment]
Yeah I agree, it should be straightforward to just render a big red button while the text is generating where the previous edit button was. I'll look into tackling that for my next PR if it hasn't been fixed by then

**Comment by transmissions11** [comment]
https://github.com/transmissions11/flux/pull/30#issuecomment-1493296665

technically closed, though with a caveat:

> hmmm ok just realized the way we've set things up, setting one node's streamId to `undefined` stops the whole stream and thus all their siblings. would have to not or conditionally abort the stream if we wanted the ability to pause generation of a specific child. i think this behavior is fine for now though, as its strictly an improvement over the status quo. good work for a future PR if folks complain :p
