### ISSUE TITLE
feat: markdown formatting

### ISSUE THREAD

**Issue by h0tw4t3r** [transmissions11/flux#24]
ChatGPT supports it, so Flux should also support it.
In difference with ChatGPT, I would enable such _Markdown Formatting_ as a **selectable** option.

It is sometimes useful to ask GPT for markdown-style results to read a better-organized response, but sometimes you need the raw markdown result (in my case it helps me with GH issues).

**Comment by transmissions11** [comment]
this seems tractable within https://github.com/transmissions11/flux/pull/19 

the notion of a separate editing and viewing state + button should enable viewing the raw markdown

**Comment by ghgoodreau** [comment]
Would we want to just parse the entire 'viewing' state as markdown, and keep the editing state as a TextareaAutosize? GPT doesn't seem to use any logic to begin and end markdown so this might be the best route. It'll just look like plaintext if there isn't any markdown syntax.

If so, I can take this on. It should fit nicely within the TextAndCodeBlock component. Feel free to assign me

**Comment by ghgoodreau** [comment]
@transmissions11 fyi ^ I'll grab this

**Comment by transmissions11** [comment]
> Would we want to just parse the entire 'viewing' state as markdown, and keep the editing state as a TextareaAutosize

yup that sounds right. a like the github comment editor we're using rn!

> If so, I can take this on. It should fit nicely within the TextAndCodeBlock component. Feel free to assign me

awesome :)

**Comment by h0tw4t3r** [comment]
![Screenshot 2023-04-07 at 23 41 16](https://user-images.githubusercontent.com/35642018/230676113-685d083d-1942-40cd-a030-31d1482259f5.png)

Just one thing, `h*` heading elements are using `--chakra-fonts-body` instead of `--chakra-fonts-heading`.

Since they are the same rn, it won't make a difference for a user. But may cause a user bug in the future.

----
Overall looks amazing! Thanks, @ghgoodreau!
