### ISSUE TITLE
feat: node color customize

### ISSUE THREAD

**Issue by HaveF** [transmissions11/flux#28]
Thanks for this repo. It's quite interesting ❤️ 

**Is your feature request related to a problem? Please describe.**
#8 rename node is an essential feature. Another feature related is node customize. 

**Describe the solution you'd like**
Customize is a bit complex, but I believe node color customize is a great feature to have, user can categorize the nodes visually by their color.

**Comment by transmissions11** [comment]
hmmm currently color is a pretty important signaler of node type, esp now that we have renaming. i think we could maybe allow color coding at the workspace level (https://github.com/transmissions11/flux/issues/18) but don't think i want to add at the node level just yet
