### ISSUE TITLE
feat: auto label nodes w/ the first X chars of their content

### ISSUE THREAD

**Issue by transmissions11** [transmissions11/flux#33]
**Is your feature request related to a problem? Please describe.**
Users find it difficult to navigate large trees without clear labels. Users have become accustomed to their conversations being essentially auto-labeled in the ChatGPT UI. Flux conversations by comparison are opaque and require more mental memory.

**Describe the solution you'd like**

Take the first X or so characters (ideally snapping to the nearest full word less than that limit) and make that the node's name, unless it has a custom label

![image](https://user-images.githubusercontent.com/26209401/229323941-d2ba84cf-9dc3-47d2-b844-6593758e691b.png)

**Describe alternatives you've considered**

We could try to use ChatGPT/etc to auto label conversations like OpenAI does in the ChatGPT ui, but I don't this will be effective on a per node basis and will be too expensive for large trees.

**Comment by jjranalli** [comment]
ChatGPT auto-label imo makes less sense when naming multiple nodes coming from a single prompt. The first X chars are a better differentiator in flux to recognise them at a glance. It might make sense to auto-label only User nodes, but would still prefer X chars for consistency.

@transmissions11 I can take care of this one

**Comment by transmissions11** [comment]
awesome, very excited to see you pick this up 🙌
