### ISSUE TITLE
fix: shift selection works on click instead of holding

### ISSUE THREAD

**Issue by h0tw4t3r** [transmissions11/flux#37]
**Platform**
MacOS, Google Chrome.

**Description**
`⇧ Shift` key selects multiple nodes not by holding a key, but just by clicking.

https://user-images.githubusercontent.com/35642018/229346651-68d0f679-fc4d-4a34-9201-787655bc195e.mov

**Comment by h0tw4t3r** [comment]
I looked into the code, and it looks like it could be `react-flow` problem.

Might be not a problem at all, but I think the all-known UX for `⇧ Shift` is selection while the key is held pressed.

I will open a bug ticket in `react-flow` and back-link it to this issue to keep track of it.

**Comment by transmissions11** [comment]
yeaaaa this seems to be an annoying quirk with react-flow. lmk if u think this makes the shift selection key more annoying than helpful for you— we can disable it.

**Comment by h0tw4t3r** [comment]
> yeaaaa this seems to be an annoying quirk with react-flow. lmk if u think this makes the shift selection key more annoying than helpful for you— we can disable it.

Not at all, it's still a rich feature, I will keep track on it on `reactflow` side.

Hopefully we resolve it relatively fast.
