### ISSUE TITLE
feat: persist size of right chat

### ISSUE THREAD

**Issue by AdamSchinzel** [transmissions11/flux#47]
**Is your feature request related to a problem? Please describe.**
It would be nice to persist the size of right chat so when I close my window and come back I still have the same size of chat that I had.

**Describe the solution you'd like**
When I reload page my right chat has the same size.

**Additional context**
We can use localStorage to persist the size.

**Comment by transmissions11** [comment]
sgtm!

**Comment by ghgoodreau** [comment]
@AdamSchinzel just merged this in #59, you can close this whenever convenient!
