### ISSUE TITLE
bug: openAI key modal is not dismissible even after pasting the token

### ISSUE THREAD

**Issue by altryne** [transmissions11/flux#5]
<img width="938" alt="CleanShot 2023-03-28 at 15 57 41@2x" src="https://user-images.githubusercontent.com/463317/228376148-24dbeb74-b0b8-4e0e-bd4a-497f49f208e1.png">

No matter what I do ,the modal won't go away. 

I refresh, the token is loaded from localhost. but the model still is not going away. 

When I remove the HTML via devtools the app seems to work fine.

**Comment by altryne** [comment]
happens in chrome and in Arc btw, with or without adblockers. Not sure what else to test, no JS errors in console

**Comment by transmissions11** [comment]
issue here is that entering your api key triggers a mixpanel event, and w/o a mixpanel token that will error.

fixed here: https://github.com/transmissions11/flux/commit/4786c4963b42dd8405d93b8d387eb8c4e0a2bdde

**Comment by altryne** [comment]
I still can't run this, cache refresh, both local (pulled latest changes) and on http://flux.paradigm.xyz 

Pasted the key, modal.. stays right there. 
Tried on Safari, Chrome and Arc 🫢 

FLUX_OPENAI_API_KEY is stored. I don't think I have a key issue, it's been in my 1P since a year ago. 

Incognito modes and all. 
![CleanShot 2023-03-28 at 17 06 54@2x](https://user-images.githubusercontent.com/463317/228386727-ea7739c3-db2d-466f-8da7-587cedf71ab7.png)

**Comment by transmissions11** [comment]
oh huh wtf— do you see any errors the console?

**Comment by transmissions11** [comment]
and are you sure you don't have an extra space or something after the token?

**Comment by altryne** [comment]
No errors 
<img width="350" alt="image" src="https://user-images.githubusercontent.com/463317/228387225-138f7f13-ef7c-4c81-a403-e588391751a6.png">

no extra spaces (I also checked 😂) 

Are you doing validation of the API key on paste? What triggers the dismissal? Maybe I can shove a breakpoint in there and see

**Comment by transmissions11** [comment]
yup this line determines if a key is "valid" or not (which triggers the dismissal)

https://github.com/transmissions11/flux/blob/af772d947237d53d0b720a75bbd2c49f83013db0/src/utils/apikey.ts#L2

**Comment by transmissions11** [comment]
the only other thing that could block the dismissal is the typing handler throwing for some reason

could in theory be this line but you'd see an error in the console

https://github.com/transmissions11/flux/blob/af772d947237d53d0b720a75bbd2c49f83013db0/src/components/modals/APIKeyModal.tsx#L22

**Comment by altryne** [comment]
Mine is 43! Maybe it's super old haha? 

<img width="444" alt="CleanShot 2023-03-28 at 17 36 19@2x" src="https://user-images.githubusercontent.com/463317/228390170-b6d57370-9199-4d61-9555-fa6de7a81743.png">

**Comment by transmissions11** [comment]
oh weird, yeah that must be it! didn't know they changed the format... TIL

**Comment by transmissions11** [comment]
we could add support for 43 char tho im worried that might introduce some confusion

**Comment by altryne** [comment]
Keep it, worst case this issue is here for ref. 
Tested with a new token and works 🔥

**Comment by transmissions11** [comment]
awesome thanks for making debugging this so easy :)
