### ISSUE TITLE
chore: automate PR descriptions with PR-Codex Github app

### ISSUE THREAD

**Issue by jjranalli** [transmissions11/flux#52]
**Is your feature request related to a problem? Please describe.**

Suggesting to automate PR descriptions with ChatGPT, for quicker reviews

**Describe the solution you'd like**

Install [PR-Codex](https://codex.dlabs.app) Github app in the repo, to summarize PR code diffs in Github discussion. More info on how it works on the website and [repo](https://github.com/decentralizedlabs/pr-codex)

**Comment by transmissions11** [comment]
oh cool sure why not

**Comment by transmissions11** [comment]
<img width="618" alt="Screenshot 2023-04-02 at 4 58 45 PM" src="https://user-images.githubusercontent.com/26209401/229386031-ed4c1ea9-e23a-4b02-92da-a8b76299aa12.png">
