### ISSUE TITLE
fix: renamed nodes are being auto-renamed once again

### ISSUE THREAD

**Issue by h0tw4t3r** [transmissions11/flux#56]
**Platform**
MacOS, Google Chrome
**Description**
When I rename the node by myself and then edit it's body, my node is being renamed once again.

As I filled the node name by hands, I would like the node to be named as I originally named it.

Affected-by #33

**Comment by transmissions11** [comment]
@h0tw4t3r we changed how we recognize which node have "custom labels" and which don't. this means all nodes given custom labels before that PR was merged are treated as normal which means they'll get overriden. this won't happen going forward and you can update your old nodes by just editing them, changing nothing, and hitting enter. sorry for the trouble!

**Comment by h0tw4t3r** [comment]
> @h0tw4t3r we changed how we recognize which nodes have "custom labels" and which don't. this means all nodes given custom labels before that PR was merged are treated as normal which means they'll get overriden. this won't happen going forward and you can update your old nodes to be marked as having custom labels by just editing them, changing nothing, and hitting enter. sorry for the trouble!

Aaah, thanks for the remark!
