### ISSUE TITLE
fix: bullet points with a space in-between them render weirdly

### ISSUE THREAD

**Issue by transmissions11** [transmissions11/flux#60]
**Platform**
Chrome — OSX

**Description**

```markdown

The following markdown:

**Flux** is really _cool_

- test

- test

1. hi

2. hi
```

Renders like so:

<img width="290" alt="Screenshot 2023-04-04 at 3 52 35 PM" src="https://user-images.githubusercontent.com/26209401/229939561-d9918c5b-2c87-4e70-9a79-6cdcd643e5db.png">

(see how the contents of the bullets are on a separate line?)

This only seems to happen when there is a full blank line between bullets

**Comment by transmissions11** [comment]
cc @ghgoodreau any chance you can take a look at this?

**Comment by transmissions11** [comment]
In general tho things do seem to render with an annoying amount space between them. i.e.

<img width="805" alt="Screenshot 2023-04-04 at 4 02 46 PM" src="https://user-images.githubusercontent.com/26209401/229940981-2757260a-f631-4f89-9c48-0c9d2153307c.png">

<img width="800" alt="Screenshot 2023-04-04 at 4 03 47 PM" src="https://user-images.githubusercontent.com/26209401/229941033-def737ae-88ed-4962-93e3-a211a6b784fe.png">

**Comment by ghgoodreau** [comment]
hmm yeah. I think we're just gonna need to go through and apply a bunch of styles. not sure why it isn't looking too great out of the box. i'm looking into it now

**Comment by ghgoodreau** [comment]
@transmissions11 draft PR up, seems to fix the spacing issue for most elements, at least on my machine. still troubleshooting the new line thing. stepping away for a bit if you wanna take a stab, but will be back to look later

**Comment by transmissions11** [comment]
closed by @ghgoodreau's PR
