### ISSUE TITLE
fix: Text garbling on long responses

### ISSUE THREAD

**Issue by DJRHails** [transmissions11/flux#66]
**Platform**
Linux - Brave

**Description**

Unsure of the precise cause of this one, but this has occurred a few times on long, code-block responses in the past few days. Using GPT-4, with certain long responses the text starts to become garbled. It feels like this is a sampling issue, or the token ids are getting mis-attributed.

![image](https://user-images.githubusercontent.com/10828202/230967871-c11a52aa-db4d-4362-9fd4-17cfe2398049.png)

I've performed an identical query from the OpenAI playground right after with zero issues, so I suspect this is a Flux specific bug. Will keep an eye out for a reproduce-able query, but thought it was worth lodging in the tracker.

**Comment by transmissions11** [comment]
I think its likely due to the default temp we select which is much higher than allowed even on the playground and not any other Flux logic
