### ISSUE TITLE
feat: allow providing custom names to the message

### ISSUE THREAD

**Issue by altryne** [transmissions11/flux#9]
Per [OpenAi cookbook](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb) it's possible to give messages custom names, and those are somehow accessible to the model? 

<img width="618" alt="image" src="https://user-images.githubusercontent.com/463317/228391894-4717fef1-609c-4981-b410-cd4ba5ff0695.png">

Would be great if naming nodes can be reflected in the UI (similar to #8 ) but if it's visible to the models, not sure I'd suggest to do it the other way around (ie, user replaces the node name for visual convinience #8 it shouldn't affect his evaluations )

**Comment by transmissions11** [comment]
hmmm personally when i played around w/ the names functionality i didn't find it very useful— and at least atm i think adding it to flux would be more of a UX confusion point than benefit, but i might reconsider with time or a strong counter example

**Comment by transmissions11** [comment]
gonna close as not planned for now just to keep things tidy
